### ISSUE TITLE
Generates an import error message - manager_core import

### ISSUE THREAD

**Issue by aurel-g** [audioscavenger/ComfyUI-Thumbnails#12]
Hi,

I got this error when launching ComfyUI :

```
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/custom_nodes/ComfyUI-Thumbnails/__init__.py", line 25, in <module>
    from .LoadImageThumbnails import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/mnt/comfyui/app/custom_nodes/ComfyUI-Thumbnails/LoadImageThumbnails.py", line 16, in <module>
    import manager_core as core
ModuleNotFoundError: No module named 'manager_core'
```

What is manager_core module ?

**Comment by audioscavenger** [comment]
fixed in v1.32!
